version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.7
    steps:
      - checkout
      - run:
          name: Pytest
          command: |
            python --version
            python3 -m venv env
            . env/bin/activate
            pip install -r requirements.txt
            pytest -v