version: 2.1
jobs:
  Test-And-Linter:
    docker:
      - image: cimg/python:3.10.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python --version
            python3 -m venv env
            . env/bin/activate
            pip install -r requirements.txt
          name: Pytest
          command: |
            pytest -v

workflows:
  Main-Workflow:
    jobs:
      - Test-And-Linter