version: 2.1

jobs:
  tests_and_linter:
    docker:
      - image: cimg/base:2021.04
        auth:
          username: deadjuju
          password: $DOCKERHUB_PASSWORD

      steps:
        - run: echo "Say hello to YAML!"
