version: 2.1
orbs:
  python: circleci/python@2.1.1
  heroku: circleci/heroku@2.0.0

jobs:
  build_and_test:
    executor: python/default  # use the default executor defined within the orb
    steps:
      - checkout  # checkout source code
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest
      - run:
          name: Run linter
          command: python -m flake8
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
      - run:
        name: echo cmd
        command: ls -la

  build_docker_image:
    docker:
      - image: cimg/python:3.10.7
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:  # create a new remote environment 
          version: 20.10.14
          docker_layer_caching: true

      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t $DOCKER_USERNAME/DOCKER_HUB_PROJECT:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push $DOCKER_USERNAME/DOCKER_HUB_PROJECT:$TAG
          echo "- READY TO DEPLOY -"


workflows:
  build_test_deploy:
    jobs:
      - build_and_test
      - build_docker_image:
          requires:
            - build_and_test
          filters:
            branches:
              only:
                - master