version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.7
    steps:
      - checkout
      - run:
          name: Pytest
          command: |
            python --version
            cat requirements.txt